import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  modalContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF',
  },
  modalCenteredView: {
    position: 'absolute',
    top: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCenteredView: {
    flex: 1,
    backgroundColor: 'hsla(0, 0%, 20%, 0.6)',
  },

  // Audience Modal
  audienceAllView: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? '17.5%' : '15%',
    left: '5%',
    width: '90%',
    backgroundColor: 'white',
    padding: '5%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    borderRadius: 5,
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  audienceTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: '5%',
    paddingBottom: '5%',
  },
  audienceListStyle: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#f9f9f9',
    paddingTop: Platform.OS === 'ios' ? '4%' : '3%',
    paddingBottom: Platform.OS === 'ios' ? '4%' : '3%',
    marginBottom: '2%',
  },
  // wallet Send Modal
  walletAllView: {
    position: 'absolute',
    // top: Platform.OS === 'ios' ? '17.5%' : '15%',
    width: '100%',
    bottom: '0%',
    height: '65%',
    backgroundColor: '#fff',
    padding: '5%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    // borderRadius: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    justifyContent: 'space-between',
  },

  walletTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: '5%',
    paddingBottom: '5%',
  },
  walletMain: {
    backgroundColor: '#f3f3f3',
    padding: '6%',
    marginBottom: '3%',
    borderRadius: 10,
  },
  walletDetailTitle: {
    fontSize: 17,
    fontWeight: '500',
    marginBottom: '2%',
  },
  walletDetailSub: {
    fontSize: 17,
  },

  // Bottom Modal
  bottomModalBG: {
    flex: 1,
    height: '60%',
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'hsla(0, 0%, 20%, 0.6)',
    paddingBottom: '5%',
  },
  bottomModal: {
    width: '90%',
    height: 50,
    backgroundColor: 'white',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    borderRadius: 50,
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    justifyContent: 'center',
  },

  // KYC Modal
  kycModal: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderColor: '#e6e6e6',
    paddingBottom: '5%',
    borderBottomWidth: 1,
    borderBottomColor: '#dddddd',
  },
  kycListView: {
    width: '90%',
    marginTop: 20,
    marginBottom: 10,
    backgroundColor: '#fff',
  },
  kycList: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  kycDot: {
    width: 5,
    height: 5,
    borderRadius: 5,
    backgroundColor: '#999',
    marginTop: 8,
    marginRight: '2%',
  },

  // List Modal
  listModal: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? '17.5%' : '12.5%',
    left: '5%',
    width: '90%',
    height: Platform.OS === 'ios' ? '65%' : '70%',
    // height: Platform.OS === 'ios' ? 600 : 500,
    backgroundColor: '#FFF',
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    borderRadius: 12,
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  listModalItem: {
    padding: 10,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  listModalImg: {
    width: 25,
    height: 16,
  },
  listModalList: {
    width: '100%',
    height: '80%',
    overflow: 'scroll',
    flexDirection: 'column',
    marginTop: 10,
  },
  listModalInputBox: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#dddddd',
    borderRadius: 13,
    marginTop: 20,
    paddingTop: '2%',
    paddingBottom: '2%',
  },
  listModalBox: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  listModalCloseButton: {
    width: 25,
    height: 25,
  },
  listModalSearch: {
    width: 25,
    height: 25,
  },

  // TextConfirmCancelModal
  tccModal: {
    position: 'absolute',
    top: '40%',
    left: '5%',
    width: '90%',
    backgroundColor: '#fff',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    borderRadius: 5,
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  tccModalBottom: {
    width: '100%',
    alignItems: 'center',
    flexDirection: 'row',
  },
  tccModalBottomButton: {
    width: '50%',
    borderBottomLeftRadius: 5,
    backgroundColor: '#ffffff',
    borderTopWidth: 0.3,
    borderTopColor: '#707070',
  },

  // TextConfrimModal
  tcModalButton: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderTopColor: '#707070',
    borderTopWidth: 0.3,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },

  // ListRoundCheckModal
  lrcModal: {
    position: 'absolute',
    top: '17.5%',
    left: '5%',
    width: '90%',
    height: '65%',
    backgroundColor: '#fff',
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    borderRadius: 5,
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  lrcmodalTop: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  lrcModalInput: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#dddddd',
    borderRadius: 5,
    marginTop: 20,
  },
  lrcModalList: {
    width: '100%',
    height: '80%',
    // overflow: 'scroll',
    flexDirection: 'column',
    marginTop: 10,
  },
  lrcItem: {
    width: '100%',
  },
  lrcItemView: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: '3%',
    paddingBottom: '3%',
  },

  // ListCheckModal
  lcModal: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? '17.5%' : '10%',
    left: '5%',
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    width: '90%',
    height: Platform.OS === 'ios' ? '65%' : '74%',
    backgroundColor: '#FFF',
    padding: '5%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    borderRadius: 12,
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  lcModalBox: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  lcModalInput: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#dddddd',
    borderRadius: 12,
    paddingLeft: '5%',
    paddingRight: '5%',
    paddingTop: '3%',
    paddingBottom: '3%',
    marginTop: '3%',
  },
});
